name: Run Python Script Daily

on:
  schedule:
    - cron: "0 7 * * *"  # Atur waktu dalam UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install yfinance

      - name: Run Python script
        run: |
          python runscript.py
